# Generated by Django 4.0.5 on 2022-06-15 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=1000)),
                ('liveLink', models.CharField(max_length=1000)),
                ('githubLink', models.CharField(max_length=1000)),
                ('techs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
            ],
        ),
    ]
